<a href="https://colab.research.google.com/github/ak2ak/tensorflow_practise/blob/master/tensorflow_2_x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [2]:
import tensorflow as tf
import numpy as np

In [7]:
a = tf.constant([[10,10],[11.,1.]])
x = tf.constant([[1.,0.],[0.,1.]])
c = tf.Variable(12.)
y = tf.matmul(a,x)+c
y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 22.],
       [23., 13.]], dtype=float32)>

In [8]:
y.numpy()

array([[22., 22.],
       [23., 13.]], dtype=float32)